### ISSUE TITLE
What's the status of the library?

### ISSUE THREAD

**Issue by Surt** [olivierandriessen/phalcon-rest#1]
Hi olivier I was taking a look at your implementation and it seems really nice. 
What is the actual status? is it ready for production?

**Comment by andevsoftware** [comment]
Hi Eric,

It's still a work in progress. I use it myself to start other projects
with. When you clone the
https://github.com/olivierandriessen/phalcon-rest-skeleton and you do
composer install & create your database with tables all of the core
functionalities will work.

For now, I recommend you to fork/clone the repo and adjust it to your
needs. If you have questions, ask. Maybe I can help you out.

Good luck ;)

2015-05-08 13:56 GMT+02:00 Erik Wiesenthal notifications@github.com:

> Hi olivier I was taking a look at your implementation and it seems really
> nice.
> What is the actual status? is it ready for production?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/olivierandriessen/phalcon-rest/issues/1.

## 

Met vriendelijke groet,

_Olivier Andriessen_
_Freelance web/app developer_

+31 (0)615669338
olivierandriessen@gmail.com
www.olivierandriessen.nl

Oostdijk 5
3255AT Oude-Tonge
Nederland

**Comment by Surt** [comment]
Great @olivierandriessen  I will do it, I like your approach very much. Thanks
