### ISSUE TITLE
1.4.2 missing defaultname for some pre-configured endpoints

### ISSUE THREAD

**Issue by gordon1210** [olivierandriessen/phalcon-rest#15]
Hi,
since 1.4.2 you need to specify a name for every endpoint created with PhalconRest\Api\Endpoint::get(), ::post(), ::put(), ::delete(), ::head(), ::options(), ::patch().

**PhalconRest\Api\Collection.php line: 125**
_$this->endpointsByName[$endpoint->getName()] = $endpoint;_

here you will always overwrite the endpoints without a name specified.

**Comment by andevsoftware** [comment]
@gordon1210 Ouch, that's pretty obvious. I will fix this asap. Thanks for letting me know.

**Comment by vip9** [comment]
Hello, any news about that?
Documentation, exports does not generates correct output. E.g. missing /user/me, or any other ::get endpoints, or . ::post are generated (when more than one).

**Comment by andevsoftware** [comment]
This issue has been resolved in v1.5.0
