### ISSUE TITLE
Problems with PUT and POST

### ISSUE THREAD

**Issue by riveraser** [olivierandriessen/phalcon-rest#19]
Hi there,

I am doing PUT "/photos/3" but CRUD wont work, its not updating values on DB.

![image](https://cloud.githubusercontent.com/assets/9339404/19795704/b0536de8-9ca3-11e6-8907-ed3411227cb7.png)

Result is "OK" but I get old values.

**Comment by andevsoftware** [comment]
Have you tried ->expectPostData() on the resource? By default it's expecting a json body.

See: https://github.com/redound/phalcon-rest/blob/master/src/PhalconRest/Api/Collection.php#L202,  https://phalcon-rest.redound.org/resources.html

**Comment by riveraser** [comment]
Yes, sorry I didn't mention it but I changed to expectPostData ()... But I tried to send json data before modifying the code and  I got same result that's why I changed to expectPostData but without success.
Thanks

**Comment by andevsoftware** [comment]
@riveraser Ok, I currently don't have time to help you out. But I would suggest you debug what's happening, maybe your server doesn't have post data enabled in some way. If the error is caused by the library just do a pull request and I will try to merge it asap. If you have questions about the library just ask.

**Comment by riveraser** [comment]
Hi Olivera, 

I will use "RAW" and "application/javascript" tu POST or PUT data:

 When sending **POST** (Create) everything is fine if I do "->expectsPostData()" and select "_form-data_" to send values... 

But when I select **PUT** (Modify) the "body" is not send in "_form-data_" format but in "_x-www-form-urlencoded_"....

So I will standardize in RAW json...

Thanks you can close the issue now if you want
