### ISSUE TITLE
developer output in json responses

### ISSUE THREAD

**Issue by reubenbrown13** [olivierandriessen/phalcon-rest#2]
When setting up the REST API for production use, it would be good to be able to disable the "developer" message in the responses when they contain an exception.  I added a basic switch statement in the Http/Response/sendException function that uses a variable that can be set in the server config.  The variable I used was debugMode (<code>'debugMode'  => 0, // 0 = off, 1 = developer messages</code>), but not the same one in the phpmailer section of the config.  This variable I set at the top of the config just after the clientHostName.  I then updated the public/index.php to pass in $config->debugMode on all the sendException calls (<code>sendException($e, $config->debugMode)</code>).  This allows for me to disable the "developer" output.  Below is the code for the sendException function.

<code>
    public function sendException($e, $debugMode=0) { 

```
    $code = $e->getCode();
    $message = $e->getMessage();

    // Use key to obtain status code
    $this->statusCode = $this->manager->getStatusCode($code);

    // Use key to obtain response message
    $message = $this->manager->getMessage($code);

    switch ($debugMode) {
        case 0:
            $this->send([
                'error' => [
                    'code' => $code,
                    'status' => $this->statusCode,
                    'message' => $message
                ]
            ]);
            break;
        case 1:
            $this->send([
                'error' => [
                    'code' => $code,
                    'status' => $this->statusCode,
                    'developer' => $e->getMessage(),
                    'message' => $message
                ]
            ]);
            break;
    }
}
```

</code>

If you think this is good to add, please do since it will make the system more production ready.

**Comment by reubenbrown13** [comment]
I just noticed that I am using an older version of the phalcon-rest code... never mind. I see you have a debugmode function there now.

**Comment by andevsoftware** [comment]
Hi @reubenbrown13,

No problem, there has changed a decent amount the last weeks. Thank you for contributing, I saw you did a pull-request. I'm looking into that too.
