### ISSUE TITLE
Response with userInfo

### ISSUE THREAD

**Issue by fili28** [olivierandriessen/phalcon-rest#21]
Hi,
I stumbled upon one minor bug.
PhalconRest\Http\Response(version 1.5.0) is not working correctly with PHP 5.x.
When I raise Exception with userInfo parameter, the Response class checks if the Exception is instance of Throwable, but Throwable class was released in PHP 7.

PhalconRest\Http\Response(version 1.4.2) :
`if ($e instanceof Exception && $e->getUserInfo() != null) {
     $error['info'] = $e->getUserInfo();
 }`

PhalconRest\Http\Response(version 1.5.0) :
`if ($e instanceof Throwable && $e->getUserInfo() != null) {
     $error['info'] = $e->getUserInfo();
 }`

So if I'm not mistaken, it's not possible to send response with info, when I use PHP 5.6 and PhalconRest 1.5.0.

**Comment by bblok11** [comment]
Thanks, this is fixed in PhalconRest 2.0
