### ISSUE TITLE
How to use Pagination?

### ISSUE THREAD

**Issue by kumy** [olivierandriessen/phalcon-rest#31]
As `phalcon-rest` use `Fractal` in internals, how it is possible to use *[pagination](http://fractal.thephpleague.com/pagination/)* feature from `Fractals`?

I've seen that an [adapter](https://github.com/thephpleague/fractal/blob/master/src/Pagination/PhalconFrameworkPaginatorAdapter.php) has been implemented for `Phalcon`. But I still can't understand how to put everything together.

Thanks.

**Comment by aprchen** [comment]
you can see this http://fractal.thephpleague.com/transformers/

**Comment by CoderPoet** [comment]
@kumy  
I solved the problem 
![image](https://user-images.githubusercontent.com/19374680/35559300-63e13b14-05e5-11e8-87da-7b431b722cf8.png)
