### ISSUE TITLE
The change from DI to Di doesn't show it, when I download the latest version (1.1.8)

### ISSUE THREAD

**Issue by wilcarjose** [olivierandriessen/phalcon-rest#5]
Hi, I cloned the boilerplate application and I installed dependencies using composer install, but I don't know why the folder name inside Phalcon REST Library (version 1.1.8)  is still DI, isn't Di.

**Comment by andevsoftware** [comment]
@wilcarjose Hi Wilcar, That change is now part of version 1.1.9 I just released. Thanks for letting us know.
