### ISSUE TITLE
Token expiration issue

### ISSUE THREAD

**Issue by fudyartanto** [olivierandriessen/phalcon-rest#7]
Thank you for your great work.
I have issue with token expiration. After debugging the system I found this: 
In the class JWTTokenParser and method create why exp = iat + exp, I think it should be exp = exp. In this class PhalconRest\Auth(), exp already time() + session duration.

Please check

**Comment by andevsoftware** [comment]
@fudyartanto Thanks! Released a patch where the token parser has been corrected. Let me know if you have any more feedback.
