### ISSUE TITLE
Parameter fields not working

### ISSUE THREAD

**Issue by esayr** [olivierandriessen/phalcon-rest#9]
when I tried

``` base
GET /photos?fields=id,title HTTP/1.1
Host: phalcon-rest.com
Authorization: Bearer eyJ0xxxxxxxx
Cache-Control: no-cache
Postman-Token: afebded1-1433-dd37-1d30-e77c674f3da1
```

and phalcon-rest response:

``` json
{
  "photos": [
    {
      "id": 1,
      "title": "Photo of Album 1",
      "albumId": 1,
      "createdAt": "2016-02-28T11:34:38Z",
      "updatedAt": "2016-02-28T11:34:38Z"
    },
    {
      "id": 2,
      "title": "Another Photo of Album 1",
      "albumId": 1,
      "createdAt": "2016-02-28T11:34:38Z",
      "updatedAt": "2016-02-28T11:34:38Z"
    },
    {
      "id": 3,
      "title": "Photo of Album 2",
      "albumId": 2,
      "createdAt": "2016-02-28T11:34:38Z",
      "updatedAt": "2016-02-28T11:34:38Z"
    }
  ]
}
```

**Comment by aisuhua** [comment]
@esayr I also have the result. I do not know it is a problem or not. So, why do you close this issue ?

**Comment by docteuri** [comment]
Yes there is an issue with this point.
Ideas to find the solution ?
Thanks

**Comment by aisuhua** [comment]
I have pull a request to fixed it.  Please see [#11](https://github.com/redound/phalcon-rest/pull/11) and [#12](https://github.com/redound/phalcon-rest/pull/12)

**Comment by vip9** [comment]
@aisuhua Your patch does not work with master:
Fatal error</b>:  Uncaught TypeError: Argument 1 passed to App\Transformers\TxxTransformer::transform() must be an instance of App\Model\Txx, instance of Phalcon\Mvc\Model\Row given, called in /api/vendor/league/fractal/src/Scope.php on line 338 and defined in /api/app/library/App/Transformers/TxxTransformer.php:11

**Comment by andevsoftware** [comment]
Fields are now enabled. However, you've to manage the missing data inside the transformer yourself. Feel free to submit a PR that will handle individual fields in the transformer.

**Comment by bigoper** [comment]
Is it related to #28 

thanks
